version: "3.9"
services:
  app:
    image: 'users-tenpo:latest'
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose_postgres
      - SPRING_DATASOURCE_USERNAME=compose_postgres
      - SPRING_DATASOURCE_PASSWORD=compose_postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - '8080:8080'

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: db
    environment:
      - POSTGRES_USER=compose_postgres
      - POSTGRES_PASSWORD=compose_postgres
      - POSTGRES_DB=compose_postgres
